libwir_la_SOURCES      += arch/tricore/optimizations/jumpcorrection/tcjumpcorrection.cc arch/tricore/optimizations/jumpcorrection/tcjumpcorrection.h

tricorejmpcorrectincludedir= ${includedir}/arch/tricore/optimizations/jumpcorrection
tricorejmpcorrectinclude_HEADERS= arch/tricore/optimizations/jumpcorrection/tcjumpcorrection.h
