libwir_la_SOURCES      += arch/tricore/optimizations/deadcode/tcdeadcode.cc arch/tricore/optimizations/deadcode/tcdeadcode.h

tricoredceincludedir    = ${includedir}/arch/tricore/optimizations/deadcode
tricoredceinclude_HEADERS= arch/tricore/optimizations/deadcode/tcdeadcode.h
