libwir_la_SOURCES	       += arch/riscv/analyses/bit/rv32bitdfa.cc arch/riscv/analyses/bit/rv32bitdfa.h

riscvbitincludedir              = ${includedir}/arch/riscv/analyses/bit
riscvbitinclude_HEADERS         = arch/riscv/analyses/bit/rv32bitdfa.h
