libwir_la_SOURCES      += arch/tricore/optimizations/constfold/tcconstfold.cc arch/tricore/optimizations/constfold/tcconstfold.h

tricorecfincludedir     = ${includedir}/arch/tricore/optimizations/constfold
tricorecfinclude_HEADERS= arch/tricore/optimizations/constfold/tcconstfold.h
