libwir_la_SOURCES      += analyses/duudchain/wirduudchainanalysis.cc analyses/duudchain/wirduudchainanalysis.h

duudincludedir          = ${includedir}/analyses/duudchain
duudinclude_HEADERS     = analyses/duudchain/wirduudchainanalysis.h
