libwir_la_SOURCES      += optimizations/siliconbugs/wirsiliconbugs.cc optimizations/siliconbugs/wirsiliconbugs.h

osiliconbugsincludedir  = ${includedir}/optimizations/siliconbugs
osiliconbugsinclude_HEADERS= optimizations/siliconbugs/wirsiliconbugs.h
