libwir_la_SOURCES      += arch/riscv/optimizations/deadcode/rvdeadcode.cc arch/riscv/optimizations/deadcode/rvdeadcode.h

riscvdceincludedir      = ${includedir}/arch/riscv/optimizations/deadcode
riscvdceinclude_HEADERS = arch/riscv/optimizations/deadcode/rvdeadcode.h
