libwir_la_SOURCES      += optimizations/loopinvariantcm/wirloopinvariantcm.cc optimizations/loopinvariantcm/wirloopinvariantcm.h

olicmincludedir         = ${includedir}/optimizations/loopinvariantcm
olicminclude_HEADERS    = optimizations/loopinvariantcm/wirloopinvariantcm.h
