libwir_la_SOURCES      += arch/tricore/optimizations/predicatedexecution/tcpredicatedexecution.cc arch/tricore/optimizations/predicatedexecution/tcpredicatedexecution.h

tricoreprexincludedir   = ${includedir}/arch/tricore/optimizations/predicatedexecution
tricoreprexinclude_HEADERS= arch/tricore/optimizations/predicatedexecution/tcpredicatedexecution.h
