libwir_la_SOURCES      += optimizations/bitopt/wirbitopt.cc optimizations/bitopt/wirbitopt.h

oboincludedir           = ${includedir}/optimizations/bitopt
oboinclude_HEADERS      = optimizations/bitopt/wirbitopt.h
