libwir_la_SOURCES      += analyses/availabledefinitions/wiravailabledefinitionsanalysis.cc analyses/availabledefinitions/wiravailabledefinitionsanalysis.h

adefincludedir          = ${includedir}/analyses/availabledefinitions
adefinclude_HEADERS     = analyses/availabledefinitions/wiravailabledefinitionsanalysis.h
